const data = {
    products: [
        {
            name: 'RAC red and white shoe',
            slug: 'rac-red-and-white',
            category: 'Shoes',
            image: 'https://images.unsplash.com/photo-1585459733425-6d1b90e0064e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80',
            price: 40,
            countInStock: 10,
            brand: 'RAC',
            rating: 4.3,
            numReviews: 35,
            description: 'fancy, longlasting shoe',
        },
        {
            name: 'Nike brown air max',
            slug: 'nike-brown-air-max',
            category: 'Shoes',
            image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=812&q=80',
            price: 65,
            countInStock: 5,
            brand: 'NIKE',
            rating: 4.9,
            numReviews: 30,
            description: 'fancy, longlasting, multipurpose shoe',
        },
        {
            name: 'Adidas boost',
            slug: 'adidas-boost',
            category: 'Shoes',
            image: 'https://images.unsplash.com/photo-1637228393230-6f7bcfb4a032?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80',
            price: 45,
            countInStock: 5,
            brand: 'ADIDAS',
            rating: 4.3,
            numReviews: 35,
            description: 'fancy, longlasting shoe',
        },
        {
            name: 'Adidas yeezy',
            slug: 'adidas-yeezy',
            category: 'Shoes',
            image: 'https://images.unsplash.com/photo-1473010350295-2c82192ebd8e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80',
            price: 70,
            countInStock: 10,
            brand: 'ADIDAS',
            rating: 4.5,
            numReviews: 15,
            description: 'fancy shoes',
        },
    ],
};

export default data;